# Generated by Django 3.2 on 2021-05-21 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='heading0',
            new_name='head0',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='heading1',
            new_name='head1',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='heading2',
            new_name='head2',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='chead0',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='chead1',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='chead2',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
